# Generated by Django 3.0.5 on 2020-06-22 23:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hardware", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Cart", "In Cart"),
                    ("Submitted", "Submitted"),
                    ("Ready for Pickup", "Ready for Pickup"),
                    ("Picked Up", "Picked Up"),
                    ("Returned", "Returned"),
                    ("Lost", "Lost"),
                ],
                default="In Cart",
                max_length=64,
            ),
        ),
    ]
