# Generated by Django 3.0.7 on 2020-08-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_auto_20200624_2137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="part_returned_health",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Healthy", "Healthy"),
                    ("Heavily Used", "Heavily Used"),
                    ("Broken", "Broken"),
                    ("Lost", "Lost"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
