# Generated by Django 3.1.12 on 2021-09-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0005_auto_20210614_0419"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="hardware_set", new_name="hardware",
        ),
    ]
