# Generated by Django 3.2.7 on 2021-11-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0006_auto_20210918_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="request",
            field=models.JSONField(default={"hardware": []}),
            preserve_default=False,
        ),
    ]
