# Generated by Django 3.2.15 on 2023-05-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0009_auto_20230214_0839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Ready for Pickup", "Ready for Pickup"),
                    ("Picked Up", "Picked Up"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Submitted",
                max_length=64,
            ),
        ),
    ]
