# Generated by Django 3.2.15 on 2023-06-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_hss_test_users"),
        ("hardware", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="event.team"
            ),
        ),
    ]
