# Generated by Django 3.2.15 on 2023-06-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reason_for_order",
            field=models.CharField(default="Hackathon Project", max_length=350),
        ),
    ]
