# Generated by Django 3.1.1 on 2020-09-10 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="mlh_conduct_agree",),
        migrations.RemoveField(model_name="application", name="mlh_data_agree",),
        migrations.RemoveField(model_name="application", name="preferred_name",),
        migrations.AddField(
            model_name="application",
            name="conduct_agree",
            field=models.BooleanField(
                default=False, help_text="I have read and agree to the code of conduct."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="data_agree",
            field=models.BooleanField(
                default=False,
                help_text="I consent to have the data in this application collected for event purposes including administration, ranking, and event communication.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("american-native", "American Indian or Alaskan Native"),
                    ("asian-pacific-islander", "Asian / Pacific Islander"),
                    ("black-african-american", "Black or African American"),
                    ("hispanic", "Hispanic"),
                    ("caucasian", "White / Caucasian"),
                    ("other", "Multiple ethnicity / Other"),
                    ("no-answer", "Prefer not to answer"),
                ],
                default="no-answer",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="graduation_year",
            field=models.IntegerField(
                default=2020,
                validators=[
                    django.core.validators.MinValueValidator(
                        2000, message="Enter a realistic graduation year."
                    ),
                    django.core.validators.MaxValueValidator(
                        2030, message="Enter a realistic graduation year."
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="school",
            field=models.CharField(default="other", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="study_level",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("highschool", "High School"),
                    ("undergraduate", "Undergraduate"),
                    ("gradschool", "Graduate School"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non-binary", "Non-binary"),
                    ("other", "Other"),
                    ("no-answer", "Prefer not to answer"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?:\\+\\d{1,3})?\\s?\\(?\\d{3}\\)?[\\s-]?\\d{3}[\\s-]?\\d{4}$",
                        message="Enter a valid phone number.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="q1",
            field=models.TextField(help_text="First question?"),
        ),
        migrations.AlterField(
            model_name="application",
            name="q2",
            field=models.TextField(help_text="Second question?"),
        ),
        migrations.AlterField(
            model_name="application",
            name="q3",
            field=models.TextField(help_text="Third question?"),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                upload_to="applications/resumes/",
                validators=[
                    registration.validators.UploadedFileValidator(
                        content_types=["application/pdf"], max_upload_size=20971520
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="registration.team",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
