# Generated by Django 3.1.1 on 2020-10-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_application_rsvp"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamReview",
            fields=[],
            options={
                "verbose_name": "Team",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("registration.team",),
        ),
    ]
