# Generated by Django 3.1.1 on 2020-09-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_application_rsvp'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('registration.team',),
        ),
    ]
