# Generated by Django 3.1.1 on 2020-09-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_teamproxy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teamproxy", options={"verbose_name": "Team"},
        ),
    ]
