# Generated by Django 3.1.1 on 2020-09-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_application_rsvp"),
        ("review", "0003_auto_20200923_2148"),
    ]

    operations = [
        migrations.DeleteModel(name="TeamProxy",),
        migrations.CreateModel(
            name="TeamReview",
            fields=[],
            options={
                "verbose_name": "Team",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("registration.team",),
        ),
    ]
