# Generated by Django 3.1.1 on 2020-09-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_auto_20200910_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="status", field=models.CharField(max_length=64),
        ),
    ]
