# Generated by Django 3.1.1 on 2020-09-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_auto_20200910_1121"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="status",),
    ]
