# Generated by Django 3.2.15 on 2022-09-12 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_hardware_site_admins_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='8022818076', max_length=20, validators=[django.core.validators.RegexValidator('^(?:\\+\\d{1,3})?\\s?\\(?\\d{3}\\)?[\\s-]?\\d{3}[\\s-]?\\d{4}$', message='Enter a valid phone number.')]),
            preserve_default=False,
        ),
    ]
