# This workflow will do a clean install of node dependencies, check formatting and run tests

name: Main Javascript Checks

on:
  push:
    branches: '*'

defaults:
  run:
    working-directory: hackathon_site/dashboard/frontend

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Formatting check
      run: yarn prettier --check 'src/**/*.js'
    - name: Tests
      run: yarn test --watchAll=false
      
