# This workflow will install Python dependencies, check formatting with Black, and run tests with Python 3.8

name: Main Python checks

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hackathon_site/requirements.txt
    - name: Check formatting with Black
      run: |
        # Stop the build if there are any formatting issues picked up by Black
        black --check .
